project:
  type: website
  output-dir: _site

website:
  title: "E. Grant Baldwin"
  site-url: "https://egrantbaldwin.com"
  navbar:
    left:
      - href: index.qmd
        text: Bio & CV
      - href: dissertation.qmd
        text: Dissertation & Job Market Paper
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme:
      light: [cosmo, custom.scss]
    css: custom.scss
    toc: false
    link-external-newwindow: true
